/**
 * Region data and initial configuration
 */

import type { Region, RegionId } from './model';

export const REGION_NAMES: Record<RegionId, string> = {
  region_a: 'Northern Grid',
  region_b: 'Solar Belt',
  region_c: 'Industrial Zone',
  region_d: 'Tech Valley',
  region_e: 'Coastal Hub',
  region_f: 'Mountain Region',
};

export const REGION_DESCRIPTIONS: Record<RegionId, string> = {
  region_a: 'Cold climate, strong grid, low renewables',
  region_b: 'Hot climate, weak grid, high solar potential',
  region_c: 'Moderate climate, strong grid, high carbon',
  region_d: 'Mild climate, tight permitting, tech-friendly',
  region_e: 'Humid climate, water stress, good wind',
  region_f: 'Cool climate, remote, hydro power',
};

// Initial region configurations
export function createInitialRegions(): Record<RegionId, Region> {
  return {
    region_a: {
      id: 'region_a',
      name: REGION_NAMES.region_a,
      gridStrengthMW: 200,
      renewablePotential: 0.3,
      waterStress: 0.2,
      permittingFriction: 0.3,
      baselineCarbonIntensity: 350,
      temperatureRisk: 0.2,
      currentGridUsageMW: 0,
      gridReserveMarginMW: 200,
      publicAcceptance: 70,
      permittingDelayWeeks: 0,
      hasHeatwave: false,
      hasBrownout: false,
      transmissionUpgradeMW: 0,
      transmissionUpgradeCompleteTick: null,
      batteryCapacityMWh: 0,
      renewablePPAMW: 0,
      communityInvestment: 0,
      dataCenterIds: [],
    },
    region_b: {
      id: 'region_b',
      name: REGION_NAMES.region_b,
      gridStrengthMW: 120,
      renewablePotential: 0.9,
      waterStress: 0.7,
      permittingFriction: 0.4,
      baselineCarbonIntensity: 200,
      temperatureRisk: 0.8,
      currentGridUsageMW: 0,
      gridReserveMarginMW: 120,
      publicAcceptance: 60,
      permittingDelayWeeks: 0,
      hasHeatwave: false,
      hasBrownout: false,
      transmissionUpgradeMW: 0,
      transmissionUpgradeCompleteTick: null,
      batteryCapacityMWh: 0,
      renewablePPAMW: 0,
      communityInvestment: 0,
      dataCenterIds: [],
    },
    region_c: {
      id: 'region_c',
      name: REGION_NAMES.region_c,
      gridStrengthMW: 300,
      renewablePotential: 0.2,
      waterStress: 0.3,
      permittingFriction: 0.2,
      baselineCarbonIntensity: 600,
      temperatureRisk: 0.4,
      currentGridUsageMW: 0,
      gridReserveMarginMW: 300,
      publicAcceptance: 75,
      permittingDelayWeeks: 0,
      hasHeatwave: false,
      hasBrownout: false,
      transmissionUpgradeMW: 0,
      transmissionUpgradeCompleteTick: null,
      batteryCapacityMWh: 0,
      renewablePPAMW: 0,
      communityInvestment: 0,
      dataCenterIds: [],
    },
    region_d: {
      id: 'region_d',
      name: REGION_NAMES.region_d,
      gridStrengthMW: 150,
      renewablePotential: 0.5,
      waterStress: 0.4,
      permittingFriction: 0.7,
      baselineCarbonIntensity: 280,
      temperatureRisk: 0.3,
      currentGridUsageMW: 0,
      gridReserveMarginMW: 150,
      publicAcceptance: 55,
      permittingDelayWeeks: 0,
      hasHeatwave: false,
      hasBrownout: false,
      transmissionUpgradeMW: 0,
      transmissionUpgradeCompleteTick: null,
      batteryCapacityMWh: 0,
      renewablePPAMW: 0,
      communityInvestment: 0,
      dataCenterIds: [],
    },
    region_e: {
      id: 'region_e',
      name: REGION_NAMES.region_e,
      gridStrengthMW: 180,
      renewablePotential: 0.7,
      waterStress: 0.8,
      permittingFriction: 0.5,
      baselineCarbonIntensity: 320,
      temperatureRisk: 0.5,
      currentGridUsageMW: 0,
      gridReserveMarginMW: 180,
      publicAcceptance: 50,
      permittingDelayWeeks: 0,
      hasHeatwave: false,
      hasBrownout: false,
      transmissionUpgradeMW: 0,
      transmissionUpgradeCompleteTick: null,
      batteryCapacityMWh: 0,
      renewablePPAMW: 0,
      communityInvestment: 0,
      dataCenterIds: [],
    },
    region_f: {
      id: 'region_f',
      name: REGION_NAMES.region_f,
      gridStrengthMW: 100,
      renewablePotential: 0.8,
      waterStress: 0.1,
      permittingFriction: 0.6,
      baselineCarbonIntensity: 100,
      temperatureRisk: 0.1,
      currentGridUsageMW: 0,
      gridReserveMarginMW: 100,
      publicAcceptance: 40,
      permittingDelayWeeks: 0,
      hasHeatwave: false,
      hasBrownout: false,
      transmissionUpgradeMW: 0,
      transmissionUpgradeCompleteTick: null,
      batteryCapacityMWh: 0,
      renewablePPAMW: 0,
      communityInvestment: 0,
      dataCenterIds: [],
    },
  };
}

// Get unlocked regions based on tutorial stage
export function getUnlockedRegions(tutorialStage: number): RegionId[] {
  if (tutorialStage < 5) {
    return ['region_a']; // Only first region in early stages
  }
  return ['region_a', 'region_b', 'region_c', 'region_d', 'region_e', 'region_f'];
}
